/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.coolmarch.worldmarkets;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sania
 */
public class PnlWorldMarkets extends javax.swing.JPanel {

    /**
     * Creates new form PnlWorldMarkets
     */
    public PnlWorldMarkets() {
        initComponents();
    }

    private void updateMarkets() {
        setToolTipText("World Markets");
        String[] indice_list = {"^IXIC","^OEX" ,"^NDX","^GSPC", "^HSI", "^JKSE",
            "^FTSE", "^GDAXI", "^FCHI", "^AORD","^OMX","^SSMI","^BFX", "^N225", "^STI", "^KS11",
            "^TWII", "^KLSE"};
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        WorldIndiceOps wop = new WorldIndiceOps();
        ArrayList<WorldIndice> al = wop.getWorldIndice(indice_list);
        Iterator i = al.iterator();
        while (i.hasNext()) {
            WorldIndice wi = (WorldIndice) i.next();
            String name = wi.getExchangeName();
            String value = wi.getExchangeLastTrade();
            String change = wi.getExchangeIndexChange();
            String dayOpen = wi.getExchangeIndexOpen();
            String dayHigh = wi.getExchangeDayHigh();
            String dayLow = wi.getExchangeDayLow();
            
            //String gloss = wi.getExchangeGainLoss();

            Vector v = new Vector();
            v.add(name);
            v.add(value);
            v.add(dayOpen);
            v.add(dayHigh);
            v.add(dayLow);
            v.add(change);
           // v.add(gloss);

            model.addRow(v);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        status = new javax.swing.JTextField();

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Value", "Day-Open", "Day-High", "Day-Low", "Change"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        jButton1.setText("Get");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        status.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        status.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 523, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        status.setText("Please wait....");
        status.update(status.getGraphics());
        status.validate();
        updateMarkets();
        status.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField status;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
