/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.coolmarch.cmnew.sectorprogress;

import java.util.Date;

/**
 *
 * @author salam
 */
public class PnlSectorPerformanceMainWindow extends javax.swing.JPanel {

    private int type = PnlSectorPerformance.DETAILED;

    /**
     * Creates new form PnlSectorPerformanceMainWindow
     */
    public PnlSectorPerformanceMainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        tfStatus = new javax.swing.JTextField();
        pnl = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton4.setText("Recent");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        tfStatus.setEditable(false);
        tfStatus.setColumns(25);
        tfStatus.setBorder(null);
        jPanel1.add(tfStatus);

        jToolBar1.add(jPanel1);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        pnl.setLayout(new java.awt.BorderLayout());
        add(pnl, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        doButton2Action();
    }//GEN-LAST:event_jButton4ActionPerformed

//    private void doButton1Action() {
//        Date d = jcDate.getDate();
//        tfStatus.setText("Please wait .....");
//        tfStatus.update(tfStatus.getGraphics());
//        tfStatus.validate();
//        PnlSectorPerformance psf = new PnlSectorPerformance(d, type);
//        pnl.removeAll();
//        pnl.add(psf);
//        pnl.update(pnl.getGraphics());
//        pnl.validate();
//        tfStatus.setText("");
//
//    }
    private void doButton2Action() {
        tfStatus.setText("Please wait .....");
        tfStatus.update(tfStatus.getGraphics());
        tfStatus.validate();
        PnlSectorPerformance psf = new PnlSectorPerformance(new Date(), PnlSectorPerformance.COMPACT);
        pnl.removeAll();
        pnl.add(psf);
        pnl.update(pnl.getGraphics());
        pnl.validate();
        tfStatus.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnl;
    private javax.swing.JTextField tfStatus;
    // End of variables declaration//GEN-END:variables
}
