/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.coolmarch.cmnew.mchart;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author salam
 */
public class CandleColorSetting extends javax.swing.JPanel {

    /**
     * Creates new form CandleColorSetting
     */
    public CandleColorSetting() {
        initComponents();
    }
    
    public Color getGainColor(){
        return btnGain.getBackground();
    }
    
    public Color getLossColor(){
        return btnLoss.getBackground();
    }
    
    public Color getOutlineColor(){
        return btnOutline.getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGain = new javax.swing.JButton();
        btnLoss = new javax.swing.JButton();
        btnOutline = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/coolmarch/cmnew/mchart/Bundle"); // NOI18N
        btnGain.setText(bundle.getString("CandleColorSetting.btnGain.text")); // NOI18N

        btnLoss.setText(bundle.getString("CandleColorSetting.btnLoss.text")); // NOI18N

        btnOutline.setText(bundle.getString("CandleColorSetting.btnOutline.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOutline)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGain)
                    .addComponent(btnLoss)
                    .addComponent(btnOutline))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


        private Color getColor(Color previousColor) {
        Color c = JColorChooser.showDialog(null, "Choose a Color",
                previousColor);
        if (c == null) {
            c = previousColor;
        }

        return c;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGain;
    private javax.swing.JButton btnLoss;
    private javax.swing.JButton btnOutline;
    // End of variables declaration//GEN-END:variables
}
