/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.coolmarch.cmnew.mchart;

import acr.component.CHyperLink;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import net.coolmarch.cmnew.res.CMResource;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author salam
 */
public class PnlCandleStickSetting extends javax.swing.JPanel {

    /**
     * Creates new form PnlCandleStickSetting
     */
    private JFreeChart chart;
    private CandleChartDetails ccd;
    private final CHyperLink lbChangeBackground, lbChangeGradient, lbChangeCandleColor,
            lbChangeVolumeBar, lbHideVolume, lbShowGridHorizentalLine,
            lbShowGridVerticalLine;

    public PnlCandleStickSetting() {
        initComponents();
        CMResource cmr = new CMResource();
        lbChangeBackground = new CHyperLink();
        lbChangeGradient = new CHyperLink();
        lbChangeCandleColor = new CHyperLink();
        lbChangeVolumeBar = new CHyperLink();
        lbHideVolume = new CHyperLink();
        lbShowGridHorizentalLine = new CHyperLink();
        lbShowGridVerticalLine = new CHyperLink();
        
        lbChangeBackground.setText("Change Background");
        lbChangeGradient.setText("Change Gradient");
        lbChangeCandleColor.setText("Change Candle Color");
        lbChangeVolumeBar.setText("Change Volume Bar Color");
        lbHideVolume.setText("Show/Hide Volume");
        lbShowGridHorizentalLine.setText("Show/Hide Horizental Grid Lines");
        lbShowGridVerticalLine.setText("Show/Hide Vertical Grid Lines");

        this.lbChangeBackground.setIcon(cmr.getIcon("backgroundFill.png"));
        this.lbChangeGradient.setIcon(cmr.getIcon("gradient16.png"));
        this.lbChangeCandleColor.setIcon(cmr.getIcon("candlestick.png"));
        this.lbChangeVolumeBar.setIcon(cmr.getIcon("volumebar16.png"));
        this.lbHideVolume.setIcon(cmr.getIcon("volumebarline.png"));
        this.lbShowGridHorizentalLine.setIcon(cmr.getIcon("horizentalGridLine16.png"));
        this.lbShowGridVerticalLine.setIcon(cmr.getIcon("verticalGridLine16.png"));

        add(lbChangeBackground);
        add(lbChangeGradient);
        add(lbChangeCandleColor);
        add(lbChangeVolumeBar);
        add(lbHideVolume);
        add(lbShowGridHorizentalLine);
        add(lbShowGridVerticalLine);

        lbChangeBackground.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                changeChartBackground();
            }
        });

        lbChangeGradient.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                changeChartGradientBackground();
            }
        });

        lbChangeCandleColor.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                flipCandleColor();
            }
        });

        lbChangeVolumeBar.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                flipVolumeColor();
            }
        });

        lbHideVolume.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                flipVolumeVisible();
            }
        });

        lbShowGridVerticalLine.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                flipVerticalGridLines();
            }
        });

        lbShowGridHorizentalLine.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                flipHorizentalGridLines();
            }
        });

    }

    public void setChart(JFreeChart chart) {
        this.chart = chart;
        ccd = new CandleChartDetails(chart);
    }

    private void changeChartBackground() {
        ccd.setMainPlotBackground();
    }

    private void changeChartGradientBackground() {
        ccd.setMainPlotBackgroundGradient();
    }

    private void flipVerticalGridLines() {
        ccd.flipDomainGridLineVisible();
    }

    private void flipHorizentalGridLines() {
        ccd.flipRangeGridLineVisible();
    }

    private void flipVolumeVisible() {
        ccd.flipVolumeBarVisibility();
    }

    private void flipVolumeColor() {
        ccd.setVolumeBarColor();
    }

    private void flipCandleColor() {
        ccd.setCandleColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modif y this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(10, 2, 0, 2));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
