/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.coolmarch.cmnew.mchart;

/**
 *
 * @author salam
 */
public class TimeFrameSelection extends javax.swing.JPanel {

    private int dayInterval = 15;
    /**
     * Creates new form TimeFrameSelection
     */
    public TimeFrameSelection() {
        initComponents();
        bg.add(c15d);
        bg.add(c30d);
        bg.add(c45d);
        bg.add(c60d);
        bg.add(c90d);
        bg.add(c3m);
        bg.add(c6m);
        bg.add(c9m);
        bg.add(c12m);
        bg.add(c1y);
        bg.add(c15y);
        bg.add(c2y);
        bg.add(c25y);
        bg.add(c3y);
        bg.add(c35y);
        bg.add(c4y);
        bg.add(c45y);
        bg.add(c5y);
        bg.add(ckall);
    }
    
    public int getSelectedDays(){
        
        int selected = 15;
        
        if(c15d.isSelected()){
            selected = 15;
        }else if(c30d.isSelected()){
            selected = 30;
        }else if(c45d.isSelected()){
            selected = 45;
        }else if(c60d.isSelected()){
            selected = 60;
        }else if(c90d.isSelected()){
            selected = 90;
        }else if(c3m.isSelected()){
            selected = 30*3;
        }else if(c6m.isSelected()){
            selected = (30*6)-48;
        }else if(c9m.isSelected()){
            selected = (30*9)-72;
        }else if(c12m.isSelected()){
            selected = (30*12)-96;
        }else if(c1y.isSelected()){
            selected = 365-96;
        }else if(c15y.isSelected()){
            selected = (365 + (6*30)) -(96+48);
        }else if(c2y.isSelected()){
            selected = 365*2 - (2*96);
        }else if(c25y.isSelected()){
            selected = ((365*2) + (6*30))-((2*96)+48);
        }else if(c3y.isSelected()){
            selected = 365*3 - (3*96);
        }else if(c35y.isSelected()){
            selected = (365*3) + (6*30) - ((3*96)+48);
        }else if(c4y.isSelected()){
            selected = 365*4 - (4*96);
        }else if(c45y.isSelected()){
            selected = 365*4 + (6*30) - ((4*96)-48);
        }else if(c5y.isSelected()){
            selected = 365*5 - (5*96);
        }else if(ckall.isSelected()){
            selected = 365*6;
        }
            
        
        return selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        c90d = new javax.swing.JCheckBox();
        c15d = new javax.swing.JCheckBox();
        c30d = new javax.swing.JCheckBox();
        c45d = new javax.swing.JCheckBox();
        c60d = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        c3m = new javax.swing.JCheckBox();
        c6m = new javax.swing.JCheckBox();
        c9m = new javax.swing.JCheckBox();
        c12m = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        c1y = new javax.swing.JCheckBox();
        c15y = new javax.swing.JCheckBox();
        c2y = new javax.swing.JCheckBox();
        c25y = new javax.swing.JCheckBox();
        c3y = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        c4y = new javax.swing.JCheckBox();
        c45y = new javax.swing.JCheckBox();
        c5y = new javax.swing.JCheckBox();
        c35y = new javax.swing.JCheckBox();
        ckall = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/coolmarch/cmnew/mchart/Bundle"); // NOI18N
        c90d.setText(bundle.getString("TimeFrameSelection.c90d.text")); // NOI18N

        c15d.setText(bundle.getString("TimeFrameSelection.c15d.text")); // NOI18N

        c30d.setText(bundle.getString("TimeFrameSelection.c30d.text")); // NOI18N

        c45d.setText(bundle.getString("TimeFrameSelection.c45d.text")); // NOI18N

        c60d.setText(bundle.getString("TimeFrameSelection.c60d.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c15d)
                    .addComponent(c30d)
                    .addComponent(c45d)
                    .addComponent(c60d)
                    .addComponent(c90d))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(c15d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c30d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c45d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c60d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c90d)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        c3m.setText(bundle.getString("TimeFrameSelection.c3m.text")); // NOI18N

        c6m.setText(bundle.getString("TimeFrameSelection.c6m.text")); // NOI18N

        c9m.setText(bundle.getString("TimeFrameSelection.c9m.text")); // NOI18N

        c12m.setText(bundle.getString("TimeFrameSelection.c12m.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c3m)
                    .addComponent(c6m)
                    .addComponent(c9m)
                    .addComponent(c12m))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(c3m)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c6m)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c9m)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c12m)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        c1y.setText(bundle.getString("TimeFrameSelection.c1y.text")); // NOI18N

        c15y.setText(bundle.getString("TimeFrameSelection.c15y.text")); // NOI18N

        c2y.setText(bundle.getString("TimeFrameSelection.c2y.text")); // NOI18N

        c25y.setText(bundle.getString("TimeFrameSelection.c25y.text")); // NOI18N

        c3y.setText(bundle.getString("TimeFrameSelection.c3y.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c1y)
                    .addComponent(c15y)
                    .addComponent(c2y)
                    .addComponent(c25y)
                    .addComponent(c3y))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(c1y)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c15y)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c2y)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c25y)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c3y)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        c4y.setText(bundle.getString("TimeFrameSelection.c4y.text")); // NOI18N

        c45y.setText(bundle.getString("TimeFrameSelection.c45y.text")); // NOI18N

        c5y.setText(bundle.getString("TimeFrameSelection.c5y.text")); // NOI18N

        c35y.setText(bundle.getString("TimeFrameSelection.c35y.text")); // NOI18N

        ckall.setText(bundle.getString("TimeFrameSelection.ckall.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c35y)
                    .addComponent(c4y)
                    .addComponent(c45y)
                    .addComponent(c5y)
                    .addComponent(ckall))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(c35y)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c4y)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c45y)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c5y)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ckall)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JCheckBox c12m;
    private javax.swing.JCheckBox c15d;
    private javax.swing.JCheckBox c15y;
    private javax.swing.JCheckBox c1y;
    private javax.swing.JCheckBox c25y;
    private javax.swing.JCheckBox c2y;
    private javax.swing.JCheckBox c30d;
    private javax.swing.JCheckBox c35y;
    private javax.swing.JCheckBox c3m;
    private javax.swing.JCheckBox c3y;
    private javax.swing.JCheckBox c45d;
    private javax.swing.JCheckBox c45y;
    private javax.swing.JCheckBox c4y;
    private javax.swing.JCheckBox c5y;
    private javax.swing.JCheckBox c60d;
    private javax.swing.JCheckBox c6m;
    private javax.swing.JCheckBox c90d;
    private javax.swing.JCheckBox c9m;
    private javax.swing.JCheckBox ckall;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
